### PR TITLE
Rename package

### PR DESCRIPTION
**Pull request by ho2ri2s**
## TL;DR

Rename package name from `com.techcafe.hoge` to `com.techcafe.todone.hoge`

### CODE REVIEW

**Comment by b4tchkn** [comment]
How did you solve it? Do you have any good references?

**Comment by ho2ri2s** [comment]
I have no good references.
I  GORIGORI move package, like this.

1. Open not `Project` but `Project Files` , you can see package hierarchy.
2. make `todone` package under the `techcafe`
3. move `repository.di` package under `todone`
4. SUCCESS!

**Comment by b4tchkn** [comment]
Oh I see. Good job!👍

**Review by b4tchkn — APPROVED** [review]
lgtm-gif-7

**Pull request merged**
